@extends('layouts.front-end.app')

@section('title',\App\CPU\translate('Return & Refund Policy'))
@push('css_or_js')
    <style>
        .headerTitle {
            font-size: 25px;
            font-weight: 700;
            margin-top: 2rem;
        }

        .for-container {
            width: 91%;
            border: 1px solid #D8D8D8;
            margin-top: 3%;
            margin-bottom: 3%;
        }

        .for-padding {
            padding: 3%;
        }


    </style>

    <meta property="og:image" content="{{asset('storage/app/public/company')}}/{{$web_config['web_logo']->value}}"/>
    <meta property="og:title" content="About {{$web_config['name']->value}} "/>
    <meta property="og:url" content="{{env('APP_URL')}}">
    <meta property="og:description" content="{!! substr($web_config['about']->value,0,100) !!}">

    <meta property="twitter:card" content="{{asset('storage/app/public/company')}}/{{$web_config['web_logo']->value}}"/>
    <meta property="twitter:title" content="about {{$web_config['name']->value}}"/>
    <meta property="twitter:url" content="{{env('APP_URL')}}">
    <meta property="twitter:description" content="{!! substr($web_config['about']->value,0,100) !!}">
@endpush
@section('content')

    <div class="container for-container rtl" style="text-align: {{Session::get('direction') === "rtl" ? 'right' : 'left'}};">
        <div class="row">
            <div class="col-md-12 sidebar_heading text-center mb-2">
                <h1 class="h3  mb-0 folot-left headerTitle">Return & Refund Policy</h1>
            </div>
        </div>
        <p>Updated at 2021-03-14</p>

        <h3>Definitions and key terms</h3>
        <p>To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are
            referenced, are strictly defined as:
        <ul>
            <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your
                browser, provide analytics, remember information about you such as your language preference or login
                information.
            </li>
            <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to YeapCart.com, that is
                responsible for your information under this Return & Refund Policy.
            </li>
            <li>Customer: refers to the company, organization or person that signs up to use the YeapCart.com Service to manage
                the relationships with your consumers or service users.
            </li>
            <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to
                visit YeapCart.com and use the services.
            </li>
            <li>Service: refers to the service provided by YeapCart.com as described in the relative terms (if available) and on
                this platform.
            </li>
            <li>Website: site, which can be accessed via this URL: https://yeapcart.com/</li>
            <li>You: a person or entity that is registered with YeapCart.com to use the Services.</li>
        </ul>
        </p>
        <h3>Return & Refund Policy</h3>
        <p>Thanks for shopping at YeapCart.com. We appreciate the fact that you like to buy the stuff we build. We also want to
            make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.</p>
        <p>As with any shopping experience, there are terms and conditions that apply to transactions at YeapCart.com. We’ll be
            as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at
            YeapCart.com, you agree to the terms set forth below along with Policy.</p>
        <p>If there’s something wrong with the you bought, or if you are not happy with it, you have 2 weeks to issue a refund
            and return your .</p>
        <p>If you would like to return a product, the only way would be if you follow the next guidelines:</p>
        <ul>
        </ul>
        <h3>Refunds</h3>
        <p>We at  ourselves to serving our customers with the best products. Every single product that you choose is thoroughly
            inspected, checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our
            products.</p>
        <p>Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our
            inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in
            advance so that you don't have to worry unnecessarily about your order. If you have purchased via Online payment
            (not Cash on Delivery), then you will be refunded once our team confirms your request.</p>
        <p>We carry out thorough quality check before processing the ordered item. We take utmost care while packing the
            product. At the same time we ensure that the packing is good such that the items won’t get damaged during transit.
            Please note that YeapCart.com is not liable for damages that are caused to the items during transit or
            transportation.</p>
        <p>We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we
            will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be
            notified when you receive your money.</p>
        <h3>Shipping</h3>
        <p>YeapCart.com is responsible for return shipping costs. Every returning shipping is paid by YeapCart.com, even if the
            item didn’t have free shipping in the first place.</p>
        <h3>Your Consent</h3>
        <p>By using our website, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy
            and agree to its terms.</p>

        <h3>Changes To Our Return & Refund Policy</h3>
        <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and
            policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to
            use the Service, you will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any
            updated Return & Refund Policy, you can delete your account.</p>

        <h3>Contact Us</h3>
        <p>If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to
            contact us and we will discuss any of the issues you are going through with our product.</p>
        <ul>
            <li>Via Email: <a href="mailto:info@yeapcart.com">info@yeapcart.com</a></li>
            <li>Via Phone Number: +919019290192</li>
            <li>Via this Link: https://yeapcart.om/contact</li>
        </ul>
    </div>

@endsection
